meta_product_name: "FusioVan"
meta_title: "FusioVan - Simplifying solar power for 'DIY' Camper Vans"
meta_description: "FusioVan is a leading provider of custom van design solutions. Thanks to our proprietary build creation tool, we help thousands of vanlifers each year to deal easily with the complexity of building a van's solar electric system. "
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
